name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: run cross-build
        uses: ahaoboy/cross-build@v1
        with:
          bin: upath
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
          tag: nightly
          allowUpdates: true